-- PDB切り替え
ALTER SESSION SET CONTAINER=XEPDB1;

-- PDBADMIN ユーザーにRESOURCE権限を付与
GRANT RESOURCE TO PDBADMIN;

-- PDBADMIN ユーザーにUSERS表領域への書き込み権限を付与
ALTER USER PDBADMIN QUOTA UNLIMITED ON USERS;

-- TABLE作成
CREATE TABLE PDBADMIN.PERSONAL (
  name VARCHAR2(64 CHAR),
  address VARCHAR2(100 CHAR),
  mobile VARCHAR2(15 CHAR)
)
TABLESPACE USERS
;
